name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaversion: ["2.11.12", "2.12.13", "2.13.4"]
        platform: ["JVM", "JS", "JS-0.6.x", "Native"]
    env:
      SCALAJS_VERSION: "${{ matrix.platform == 'JS-0.6.x' && '0.6.33' || '' }}"
      PROJECT_NAME: "portable-scala-reflect${{ matrix.platform == 'JS-0.6.x' && 'JS' || matrix.platform }}"
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v5
      - name: Formatting
        run: sbt lint
      - name: Unit tests
        run: sbt "++${{ matrix.scalaversion }}" "${{ env.PROJECT_NAME }}/test"
      - name: Test generate documentation
        run: sbt "++${{ matrix.scalaversion }}" "${{ env.PROJECT_NAME }}/doc"
      - name: MiMa
        run: sbt "++${{ matrix.scalaversion }}" "${{ env.PROJECT_NAME }}/mimaReportBinaryIssues"
