name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaversion: ["2.12.19", "2.13.13"]
        platform: ["JVM", "JS", "Native"]
    env:
      PROJECT_NAME: "portable-scala-reflect${{ matrix.platform }}"
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v5
      - name: Unit tests
        run: sbt "++${{ matrix.scalaversion }}" "${{ env.PROJECT_NAME }}/test"
      - name: Test generate documentation
        run: sbt "++${{ matrix.scalaversion }}" "${{ env.PROJECT_NAME }}/doc"
      - name: MiMa
        run: sbt "++${{ matrix.scalaversion }}" "${{ env.PROJECT_NAME }}/mimaReportBinaryIssues"
